######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 11 14:35:49 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              RenderArea \
              RenderArea/notes \
              RenderArea/calendars/onePagePerDay \
              RenderArea/calendars/onePagePerMonth \
              RenderArea/calendars/onePagePerWeek \
              RenderArea/calendars/onePagePerYear \
              RenderArea/calendars/twoPagePerDay \
              RenderArea/calendars/twoPagePerMonth \
              RenderArea/calendars/twoPagePerWeek \
              RenderArea/calendars/twoPagePerYear
INCLUDEPATH += .
QT += svg
QMAKE_MAC_SDK=/Developer/SDKs/MacOSX10.4u.sdk
CONFIG+= x86 ppc

# 
# Used to check the translations
# DEFINES += QT_NO_CAST_FROM_ASCII

# Input
HEADERS += MyWindow.h RenderArea.h
SOURCES += main.cpp \
           MyWindow--createCalendarTab.cpp \
           MyWindow--createChartsTab.cpp \
           MyWindow--createChecklistsTab.cpp \
           MyWindow--createLinesTab.cpp \
           MyWindow--createNotesTab.cpp \
           MyWindow--createPageSizeTab.cpp \
           MyWindow--createTemplateTab.cpp \
           MyWindow.cpp \
           RenderArea.cpp \
           RenderArea/RenderArea--draw.cpp \
           RenderArea/RenderArea--drawAppointmentRow.cpp \
           RenderArea/RenderArea--drawBar.cpp \
           RenderArea/RenderArea--drawGradientBox.cpp \
           RenderArea/RenderArea--drawLittleMonth.cpp \
           RenderArea/RenderArea--drawOneShortDay.cpp \
           RenderArea/RenderArea--drawRow.cpp \
           RenderArea/RenderArea--drawShadowedRect.cpp \
           RenderArea/RenderArea--drawSubHeader.cpp \
           RenderArea/RenderArea--fitRectToString.cpp \
           RenderArea/RenderArea--fitStringInRect.cpp \
           RenderArea/RenderArea--sets.cpp \
           RenderArea/notes/drawSinglePageNotes.cpp \
           RenderArea/calendars/onePagePerDay/onePagePerDayDrawPage.cpp \
           RenderArea/calendars/onePagePerMonth/onePagePerMonthDrawPage.cpp \
           RenderArea/calendars/onePagePerWeek/onePagePerWeekDrawPage.cpp \
           RenderArea/calendars/onePagePerYear/onePagePerTwoYearsDrawPage.cpp \
           RenderArea/calendars/onePagePerYear/onePagePerYearDrawPage.cpp \
           RenderArea/calendars/twoPagePerDay/twoPagePerDayDrawDay.cpp \
           RenderArea/calendars/twoPagePerDay/twoPagePerDayDrawOtherPage.cpp \
           RenderArea/calendars/twoPagePerMonth/twoPagePerMonthDrawOneDay.cpp \
           RenderArea/calendars/twoPagePerMonth/twoPagePerMonthDrawPage.cpp \
           RenderArea/calendars/twoPagePerWeek/twoPagePerWeekDrawOneDay.cpp \
           RenderArea/calendars/twoPagePerWeek/twoPagePerWeekDrawPage.cpp \
           RenderArea/calendars/twoPagePerWeek/twoPagePerWeekMoleskineStyleDrawPage.cpp \
           RenderArea/calendars/twoPagePerYear/twoPagePerYearDrawOneDay.cpp \
           RenderArea/calendars/twoPagePerYear/twoPagePerYearDrawPage.cpp
